name: Package Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip folder
        run: cd .. && zip -r ${{ github.event.repository.name }}-${{ github.ref_name }}.zip ${{ github.event.repository.name }} -x ${{ github.event.repository.name }}/.git/\* ${{ github.event.repository.name }}/.github/\* ${{ github.event.repository.name }}/.vscode/\* \*.bat \*.png \*.md \*.txt

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          files: ../${{ github.event.repository.name }}-${{ github.ref_name }}.zip
          generate_release_notes: true
