name: Release

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip folder
        run: zip -r BetterBags_ItemRack.zip . -x .git/\* .github/\* .vscode/\* \*.bat icon.png

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          files: BetterBags_ItemRack-${{ github.ref }}.zip
